name: Publish website changes

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      skip-tests:
        description: Skip Integration Tests
        required: true
        default: false
        type: boolean

jobs:
  test:
    name: Integration Tests
    if: ${{ github.event.inputs.skip-tests == 'false' }}
    strategy:
      fail-fast: true
      matrix:
        browser: [electron, firefox, chrome] #Optional: Beta builds?
        viewport: [default, 1080p, samsung-s10]
        include:
          - viewport: default
            viewport_width: 1000 # Default
            viewport_height: 660
          - viewport: 1080p
            viewport_width: 1920 # 1080p
            viewport_height: 1080
          - viewport: samsung-s10
            viewport_width: 360 # samsung-s10
            viewport_height: 760
    runs-on: ubuntu-latest
    steps:
      # Checkout git branch
      - name: Checkout
        uses: actions/checkout@v3.0.2

      # Automatic setup of Ruby environment and dependencies
      - name: Perform Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # Automatic installation of node, modules, building and serving site
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: bundle exec jekyll serve --no-watch # No changes should happen -> no need to watch
          wait-on: 'http://localhost:4000' # Ensure server comes up before tests start, in case build takes longer
          browser: ${{ matrix.browser }}
          config: viewportHeight=${{ matrix.viewport_height }},viewportWidth=${{ matrix.viewport_width }}

  verify:
    name: Integration Tests Completed
    if: ${{ github.event.inputs.skip-tests == 'false' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Verify Matrix Test Result
        if: ${{ needs.test.result != 'success' }}
        run: echo "Tests failed!" && exit 1

  publish:
    name: Publish Website Changes
    needs: verify
    runs-on: ubuntu-latest
    if: ${{ always () }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Push changes to Publish branch
        if: ${{ !github.events.inputs.skip-tests || needs.verify.result == 'success' }}
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          target_branch: publish
          github_token: ${{ github.token }}
    
